# Site settings
title: The Daily Quibbler
name: Edna Morales
email: edna592@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Software Developer @ IBM. VT Hokie. Muggle.
  Writing about all things that interest me.
baseurl: "" # the subpath of your site, e.g. /blog/
url: "http://ednamorales.co" # the base hostname & protocol for your site
twitter_username: ednaymorales
github_username:  eymorale
linkedin_username: eymorale

# Build settings
markdown: kramdown
